name: familiens_receptbok
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.6.0
  path_provider: ^2.1.5
  riverpod: ^2.6.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.11

dependency_overrides:
  meta: ^1.15.0
  analyzer: ^6.4.1

flutter:
  generate: true
  uses-material-design: true
